name: SteveLents
favicon: null
layout_spectrum: 0.5077033422421664
typography_spectrum: 0.8131993787828833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8948922895360738
  lightness: 0.9498168544378132
  saturation: 0.3897710347082466
  rhythmicContrast: 0.8235729150474072
purpose: []
